title: Leap Day theme
description: Leap Day is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
include: ["_pages"]
permalink: /:title/

sass:
    load_paths:
        - _sass
        - node_modules

exclude: []